ClusterName=ang-dev-multinode
SlurmctldHost=slurmctld
AuthType=auth/munge
CryptoType=crypto/munge
MpiDefault=none
ProctrackType=proctrack/linuxproc
ReturnToService=1
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmdPidFile=/var/run/slurmd.pid
SlurmdSpoolDir=/var/spool/slurmd
SlurmUser=slurm
StateSaveLocation=/var/spool/slurmctld
SwitchType=switch/none
TaskPlugin=task/none

SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurm/slurmd.log

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core

NodeName=node1 CPUs=1 State=UNKNOWN
NodeName=node2 CPUs=1 State=UNKNOWN
NodeName=node3 CPUs=1 State=UNKNOWN
NodeName=node4 CPUs=1 State=UNKNOWN
NodeName=node5 CPUs=1 State=UNKNOWN
NodeName=node6 CPUs=1 State=UNKNOWN
NodeName=node7 CPUs=1 State=UNKNOWN
NodeName=node8 CPUs=1 State=UNKNOWN
PartitionName=debug Nodes=node1,node2,node3,node4,node5,node6,node7,node8 Default=YES MaxTime=INFINITE State=UP

Prolog=/etc/slurm/ang-hooks/prolog.sh
TaskProlog=/etc/slurm/ang-hooks/task-prolog.sh
TaskEpilog=/etc/slurm/ang-hooks/task-epilog.sh
EpilogSlurmctld=/etc/slurm/ang-hooks/epilog-slurmctld.sh
